/**
 * Generates `src/page/my-settings/appearance/illustrations.ts` from the legacy display-mode
 * illustrations (`components/modals/appearances.tsx`), the same way `generate-icons.ts` does:
 *   bun run scripts/generate-appearance-illustrations.ts
 */
import { writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { htmlChildrenToFoldkit } from "../../../packages/ui-parity/src/codegen.ts"

const legacyRoot = resolve(import.meta.dir, "../../web")
const { createElement } = await import(Bun.resolveSync("react", legacyRoot))
const { renderToStaticMarkup } = await import(Bun.resolveSync("react-dom/server", legacyRoot))
const module = await import(resolve(legacyRoot, "src/components/modals/appearances.tsx"))

const out: string[] = [
	"// Generated by scripts/generate-appearance-illustrations.ts from apps/web/src/components/modals/appearances.tsx. Do not edit.",
	'import type { Html, HtmlBuilder } from "foldkit/html"',
	"",
	"const illustration = <Message>(h: HtmlBuilder<Message>, root: Readonly<Record<string, string>>, className: string, children: Html[]): Html =>",
	"\th.svg(",
	"\t\t[...Object.entries(root).map(([key, value]) => h.Attribute(key, value)), h.Class(className)],",
	"\t\tchildren,",
	"\t)",
	"",
]
for (const name of ["System", "Light", "Dark"]) {
	const markup = renderToStaticMarkup(createElement(module[name], {}))
	const { rootAttributes, children } = htmlChildrenToFoldkit(markup, 2)
	const root = Object.fromEntries(
		rootAttributes.map((attr) => [attr.name === "viewbox" ? "viewBox" : attr.name, attr.value]),
	)
	out.push(
		`export const ${name} = <Message>(h: HtmlBuilder<Message>, className: string): Html =>`,
		`\tillustration(h, ${JSON.stringify(root)}, className, [\n${children.join(",\n")},\n\t])`,
		"",
	)
}
writeFileSync(resolve(import.meta.dir, "../src/page/my-settings/appearance/illustrations.ts"), out.join("\n"))
console.log("generated 3 illustrations")
