/**
 * Generates `src/chat/file-icons.ts` from `@untitledui/file-icons`' React `FileIcon`.
 *
 * Every supported type (plus the "empty" fallback) is rendered to static SVG with
 * react-dom/server from apps/web's own dependencies, then stored as a compact element tree:
 *   bun run scripts/generate-file-icons.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import type { DefaultTreeAdapterMap } from "parse5"

type Node = DefaultTreeAdapterMap["childNode"]
type Element = DefaultTreeAdapterMap["element"]
type Tree = readonly [string, Readonly<Record<string, string>>, ReadonlyArray<Tree | string>]

const legacyRoot = resolve(import.meta.dir, "../../web")
const { createElement } = await import(Bun.resolveSync("react", legacyRoot))
const { renderToStaticMarkup } = await import(Bun.resolveSync("react-dom/server", legacyRoot))
// parse5 is a dependency of the parity package, like the codegen generate-icons.ts uses.
const { parseFragment } = await import(
	Bun.resolveSync("parse5", resolve(import.meta.dir, "../../../packages/ui-parity"))
)
const { FileIcon, SUPPORTED_FILE_TYPES } = await import(
	Bun.resolveSync("@untitledui/file-icons/dist/FileIcon.mjs", legacyRoot)
)

// parse5 lowercases SVG attribute and tag names; restore the camelCase ones.
const SVG_CASE: Record<string, string> = {
	viewbox: "viewBox",
	clippath: "clipPath",
	lineargradient: "linearGradient",
	radialgradient: "radialGradient",
	gradientunits: "gradientUnits",
	gradienttransform: "gradientTransform",
}

const toTree = (element: Element): Tree => [
	SVG_CASE[element.tagName] ?? element.tagName,
	Object.fromEntries(element.attrs.map((attr) => [SVG_CASE[attr.name] ?? attr.name, attr.value])),
	(element.childNodes as Node[]).flatMap((child): Array<Tree | string> => {
		if ("tagName" in child) return [toTree(child as Element)]
		if (child.nodeName === "#text") {
			const text = (child as DefaultTreeAdapterMap["textNode"]).value
			return text.trim() ? [text] : []
		}
		return []
	}),
]

const render = (type: string): Tree => {
	const markup = renderToStaticMarkup(createElement(FileIcon, { type }))
	const root = parseFragment(markup).childNodes.find((node) => "tagName" in node)
	if (!root) throw new Error(`generate-file-icons: no svg for ${type}`)
	return toTree(root as Element)
}

const types: ReadonlyArray<string> = SUPPORTED_FILE_TYPES
const trees = new Map(types.map((type) => [type, render(type)]))
const tags = new Set<string>()
const collectTags = ([tag, , children]: Tree): void => {
	tags.add(tag)
	for (const child of children) if (typeof child !== "string") collectTags(child)
}
for (const tree of trees.values()) collectTags(tree)

const out: string[] = [
	"// Generated by scripts/generate-file-icons.ts from @untitledui/file-icons. Do not edit.",
	'import type { Html, HtmlBuilder } from "foldkit/html"',
	"",
	`type Tag = ${[...tags].map((tag) => JSON.stringify(tag)).join(" | ")}`,
	"type Tree = readonly [Tag, Readonly<Record<string, string>>, ReadonlyArray<Tree | string>]",
	"",
	"export const SUPPORTED_FILE_TYPES: ReadonlyArray<string> = " + JSON.stringify(types),
	"",
	"/** The FileIcon `default` variant, light theme, keyed by type. */",
	"const icons: Readonly<Record<string, Tree>> = {",
	...[...trees].map(([type, tree]) => `\t${JSON.stringify(type)}: ${JSON.stringify(tree)},`),
	"}",
	"",
	"// FileIcon resolves a MIME type to its category (`categorizeMimeType`).",
	`const codeSubtypes = ${JSON.stringify(mimeList("code"))}`,
	`const documentSubtypes = ${JSON.stringify(mimeList("document"))}`,
	"const categorize = (mime: string) => {",
	'\tconst [kind, subtype] = mime.split("/")',
	'\tif (!kind || !subtype) return "unknown"',
	'\tif (kind === "image" || kind === "audio" || kind === "video") return kind',
	'\tif (kind === "application" || kind === "text") {',
	'\t\tif (codeSubtypes.includes(subtype)) return "code"',
	'\t\tif (documentSubtypes.includes(subtype)) return "document"',
	"\t}",
	'\treturn "unknown"',
	"}",
	"",
	"/** FileIcon's type resolution: a known type, a MIME category, else `empty`. */",
	"const resolveType = (type: string) => {",
	'\tconst isMime = type.includes("/")',
	'\tconst subtype = (isMime ? type.split("/")[1] : undefined) ?? type',
	"\tif (SUPPORTED_FILE_TYPES.includes(subtype)) return subtype",
	"\tconst category = isMime ? categorize(type) : undefined",
	'\treturn category !== undefined && SUPPORTED_FILE_TYPES.includes(category) ? category : "empty"',
	"}",
	"",
	"const renderTree = <Message>(h: HtmlBuilder<Message>, [tag, attributes, children]: Tree, className?: string): Html =>",
	"\th[tag](",
	"\t\t[",
	"\t\t\t...Object.entries(attributes).map(([key, value]) => h.Attribute(key, value)),",
	"\t\t\t...(className ? [h.Class(className)] : []),",
	"\t\t],",
	'\t\tchildren.map((child) => (typeof child === "string" ? child : renderTree(h, child))),',
	"\t)",
	"",
	"/** Port of `<FileIcon type={type} className={className} />`. */",
	"export const fileIcon = <Message>(",
	"\th: HtmlBuilder<Message>,",
	"\ttype: string,",
	"\toptions: { readonly className?: string } = {},",
	"): Html => renderTree(h, icons[resolveType(type)] ?? icons.empty!, options.className)",
	"",
]

function mimeList(kind: "code" | "document"): ReadonlyArray<string> {
	const text = readFileSync(Bun.resolveSync("@untitledui/file-icons/dist/FileIcon.mjs", legacyRoot), "utf8")
	const lists = [...text.matchAll(/=\[("[^\]]*")\]/g)].map(
		(match) => JSON.parse(`[${match[1]}]`) as string[],
	)
	const found = lists.find((list) =>
		kind === "code" ? list.includes("typescript") : list.includes("msword"),
	)
	if (!found) throw new Error(`generate-file-icons: no ${kind} MIME list`)
	return found
}

const target = resolve(import.meta.dir, "../src/chat/file-icons.ts")
writeFileSync(target, out.join("\n"))
// Format like the rest of the repo so a rerun produces no diff.
Bun.spawnSync(["bunx", "oxfmt", target], { cwd: resolve(import.meta.dir, "../../..") })
console.log(`generated ${types.length} file icons`)
