/**
 * Generates `src/icons/index.ts` from the legacy React icon components.
 *
 * Each icon is rendered to static SVG with react-dom/server (from apps/web's own
 * dependencies), then translated to Foldkit view code. Run after legacy icons change:
 *   bun run scripts/generate-icons.ts
 */
import { readdirSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { htmlChildrenToFoldkit } from "../../../packages/ui-parity/src/codegen.ts"

const legacyRoot = resolve(import.meta.dir, "../../web")
const iconsDir = resolve(legacyRoot, "src/components/icons")
const { createElement } = await import(Bun.resolveSync("react", legacyRoot))
const { renderToStaticMarkup } = await import(Bun.resolveSync("react-dom/server", legacyRoot))

const icons = new Map<string, string>()
for (const file of readdirSync(iconsDir)
	.filter((name) => name.endsWith(".tsx"))
	.sort()) {
	const module = await import(resolve(iconsDir, file))
	for (const [exportName, component] of Object.entries(module)) {
		if (exportName === "default" || typeof component !== "function" || !/^Icon/.test(exportName)) continue
		icons.set(exportName, renderToStaticMarkup(createElement(component as never, {})))
	}
	// Default-only exports: name them after the file.
	if (
		module.default &&
		![...Object.values(module)].some(
			(value, index) => Object.keys(module)[index] !== "default" && value === module.default,
		)
	) {
		const name = file
			.replace(/\.tsx$/, "")
			.split("-")
			.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
			.join("")
			.replace(/[^A-Za-z0-9]/g, "")
		if (!icons.has(name)) icons.set(name, renderToStaticMarkup(createElement(module.default, {})))
	}
}

// The logo is an icon-shaped component outside the icons directory.
const { Logo } = await import(resolve(legacyRoot, "src/components/logo.tsx"))
icons.set("Logo", renderToStaticMarkup(createElement(Logo, {})))

const out: string[] = [
	"// Generated by scripts/generate-icons.ts from apps/web/src/components/icons. Do not edit.",
	'import type { Html, HtmlBuilder } from "foldkit/html"',
	"",
	"export interface IconOptions {",
	"\t/** Extra classes, appended like React's `className` prop. */",
	"\treadonly className?: string",
	"\t/** Overrides (or with `null` removes) root attributes, like spreading props in the legacy component. */",
	"\treadonly attributes?: Readonly<Record<string, string | null>>",
	"}",
	"",
	"const icon = <Message>(h: HtmlBuilder<Message>, root: Readonly<Record<string, string>>, options: IconOptions, children: Html[]): Html => {",
	"\tconst attributes: Record<string, string | null> = { ...root, ...options.attributes }",
	"\tif (options.className) attributes.class = options.className",
	"\treturn h.svg(",
	"\t\tObject.entries(attributes)",
	"\t\t\t.filter((entry): entry is [string, string] => entry[1] !== null)",
	'\t\t\t.map(([key, value]) => (key === "class" ? h.Class(value) : h.Attribute(key, value))),',
	"\t\tchildren,",
	"\t)",
	"}",
	"",
]
for (const [name, markup] of icons) {
	const { rootAttributes, children } = htmlChildrenToFoldkit(markup, 2)
	const root = Object.fromEntries(
		rootAttributes.map((attr) => [attr.name === "viewbox" ? "viewBox" : attr.name, attr.value]),
	)
	out.push(
		`export const ${name} = <Message>(h: HtmlBuilder<Message>, options: IconOptions = {}): Html =>`,
		`\ticon(h, ${JSON.stringify(root)}, options, [\n${children.join(",\n")},\n\t])`,
		"",
	)
}
writeFileSync(resolve(import.meta.dir, "../src/icons/index.ts"), out.join("\n"))
console.log(`generated ${icons.size} icons`)
